/*
sdk_api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetSellableItemStockERC721Id200ResponseData struct for GetSellableItemStockERC721Id200ResponseData
type GetSellableItemStockERC721Id200ResponseData struct {
	ItemStockId string `json:"itemStockId"`
}

// NewGetSellableItemStockERC721Id200ResponseData instantiates a new GetSellableItemStockERC721Id200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSellableItemStockERC721Id200ResponseData(itemStockId string) *GetSellableItemStockERC721Id200ResponseData {
	this := GetSellableItemStockERC721Id200ResponseData{}
	this.ItemStockId = itemStockId
	return &this
}

// NewGetSellableItemStockERC721Id200ResponseDataWithDefaults instantiates a new GetSellableItemStockERC721Id200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSellableItemStockERC721Id200ResponseDataWithDefaults() *GetSellableItemStockERC721Id200ResponseData {
	this := GetSellableItemStockERC721Id200ResponseData{}
	return &this
}

// GetItemStockId returns the ItemStockId field value
func (o *GetSellableItemStockERC721Id200ResponseData) GetItemStockId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ItemStockId
}

// GetItemStockIdOk returns a tuple with the ItemStockId field value
// and a boolean to check if the value has been set.
func (o *GetSellableItemStockERC721Id200ResponseData) GetItemStockIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ItemStockId, true
}

// SetItemStockId sets field value
func (o *GetSellableItemStockERC721Id200ResponseData) SetItemStockId(v string) {
	o.ItemStockId = v
}

func (o GetSellableItemStockERC721Id200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["itemStockId"] = o.ItemStockId
	}
	return json.Marshal(toSerialize)
}

type NullableGetSellableItemStockERC721Id200ResponseData struct {
	value *GetSellableItemStockERC721Id200ResponseData
	isSet bool
}

func (v NullableGetSellableItemStockERC721Id200ResponseData) Get() *GetSellableItemStockERC721Id200ResponseData {
	return v.value
}

func (v *NullableGetSellableItemStockERC721Id200ResponseData) Set(val *GetSellableItemStockERC721Id200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSellableItemStockERC721Id200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSellableItemStockERC721Id200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSellableItemStockERC721Id200ResponseData(val *GetSellableItemStockERC721Id200ResponseData) *NullableGetSellableItemStockERC721Id200ResponseData {
	return &NullableGetSellableItemStockERC721Id200ResponseData{value: val, isSet: true}
}

func (v NullableGetSellableItemStockERC721Id200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSellableItemStockERC721Id200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


