/*
 * sdk_api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InlineResponse20019 struct for InlineResponse20019
type InlineResponse20019 struct {
	// クライアント側でloadStripeに対して渡す公開可能なAPI-Key
	PublishableKey string `json:"publishableKey"`
	// StripeのPaymentIntentのClientSecret
	Secret string `json:"secret"`
}

// NewInlineResponse20019 instantiates a new InlineResponse20019 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse20019(publishableKey string, secret string) *InlineResponse20019 {
	this := InlineResponse20019{}
	this.PublishableKey = publishableKey
	this.Secret = secret
	return &this
}

// NewInlineResponse20019WithDefaults instantiates a new InlineResponse20019 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse20019WithDefaults() *InlineResponse20019 {
	this := InlineResponse20019{}
	return &this
}

// GetPublishableKey returns the PublishableKey field value
func (o *InlineResponse20019) GetPublishableKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PublishableKey
}

// GetPublishableKeyOk returns a tuple with the PublishableKey field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20019) GetPublishableKeyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PublishableKey, true
}

// SetPublishableKey sets field value
func (o *InlineResponse20019) SetPublishableKey(v string) {
	o.PublishableKey = v
}

// GetSecret returns the Secret field value
func (o *InlineResponse20019) GetSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Secret
}

// GetSecretOk returns a tuple with the Secret field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20019) GetSecretOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Secret, true
}

// SetSecret sets field value
func (o *InlineResponse20019) SetSecret(v string) {
	o.Secret = v
}

func (o InlineResponse20019) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["publishableKey"] = o.PublishableKey
	}
	if true {
		toSerialize["secret"] = o.Secret
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse20019 struct {
	value *InlineResponse20019
	isSet bool
}

func (v NullableInlineResponse20019) Get() *InlineResponse20019 {
	return v.value
}

func (v *NullableInlineResponse20019) Set(val *InlineResponse20019) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse20019) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse20019) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse20019(val *InlineResponse20019) *NullableInlineResponse20019 {
	return &NullableInlineResponse20019{value: val, isSet: true}
}

func (v NullableInlineResponse20019) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse20019) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


