/*
sdk_api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetContractERC721ById200Response struct for GetContractERC721ById200Response
type GetContractERC721ById200Response struct {
	Data ContractERC721 `json:"data"`
	Meta map[string]interface{} `json:"meta"`
}

// NewGetContractERC721ById200Response instantiates a new GetContractERC721ById200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetContractERC721ById200Response(data ContractERC721, meta map[string]interface{}) *GetContractERC721ById200Response {
	this := GetContractERC721ById200Response{}
	this.Data = data
	this.Meta = meta
	return &this
}

// NewGetContractERC721ById200ResponseWithDefaults instantiates a new GetContractERC721ById200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetContractERC721ById200ResponseWithDefaults() *GetContractERC721ById200Response {
	this := GetContractERC721ById200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetContractERC721ById200Response) GetData() ContractERC721 {
	if o == nil {
		var ret ContractERC721
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetContractERC721ById200Response) GetDataOk() (*ContractERC721, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetContractERC721ById200Response) SetData(v ContractERC721) {
	o.Data = v
}

// GetMeta returns the Meta field value
func (o *GetContractERC721ById200Response) GetMeta() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *GetContractERC721ById200Response) GetMetaOk() (map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Meta, true
}

// SetMeta sets field value
func (o *GetContractERC721ById200Response) SetMeta(v map[string]interface{}) {
	o.Meta = v
}

func (o GetContractERC721ById200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	if true {
		toSerialize["meta"] = o.Meta
	}
	return json.Marshal(toSerialize)
}

type NullableGetContractERC721ById200Response struct {
	value *GetContractERC721ById200Response
	isSet bool
}

func (v NullableGetContractERC721ById200Response) Get() *GetContractERC721ById200Response {
	return v.value
}

func (v *NullableGetContractERC721ById200Response) Set(val *GetContractERC721ById200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetContractERC721ById200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetContractERC721ById200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetContractERC721ById200Response(val *GetContractERC721ById200Response) *NullableGetContractERC721ById200Response {
	return &NullableGetContractERC721ById200Response{value: val, isSet: true}
}

func (v NullableGetContractERC721ById200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetContractERC721ById200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


