/*
 * sdk_api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InlineResponse20015Data struct for InlineResponse20015Data
type InlineResponse20015Data struct {
	Profile WalletAddressProfile `json:"profile"`
	AvatarImageUrl string `json:"avatarImageUrl"`
}

// NewInlineResponse20015Data instantiates a new InlineResponse20015Data object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse20015Data(profile WalletAddressProfile, avatarImageUrl string) *InlineResponse20015Data {
	this := InlineResponse20015Data{}
	this.Profile = profile
	this.AvatarImageUrl = avatarImageUrl
	return &this
}

// NewInlineResponse20015DataWithDefaults instantiates a new InlineResponse20015Data object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse20015DataWithDefaults() *InlineResponse20015Data {
	this := InlineResponse20015Data{}
	return &this
}

// GetProfile returns the Profile field value
func (o *InlineResponse20015Data) GetProfile() WalletAddressProfile {
	if o == nil {
		var ret WalletAddressProfile
		return ret
	}

	return o.Profile
}

// GetProfileOk returns a tuple with the Profile field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20015Data) GetProfileOk() (*WalletAddressProfile, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Profile, true
}

// SetProfile sets field value
func (o *InlineResponse20015Data) SetProfile(v WalletAddressProfile) {
	o.Profile = v
}

// GetAvatarImageUrl returns the AvatarImageUrl field value
func (o *InlineResponse20015Data) GetAvatarImageUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AvatarImageUrl
}

// GetAvatarImageUrlOk returns a tuple with the AvatarImageUrl field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20015Data) GetAvatarImageUrlOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.AvatarImageUrl, true
}

// SetAvatarImageUrl sets field value
func (o *InlineResponse20015Data) SetAvatarImageUrl(v string) {
	o.AvatarImageUrl = v
}

func (o InlineResponse20015Data) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["profile"] = o.Profile
	}
	if true {
		toSerialize["avatarImageUrl"] = o.AvatarImageUrl
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse20015Data struct {
	value *InlineResponse20015Data
	isSet bool
}

func (v NullableInlineResponse20015Data) Get() *InlineResponse20015Data {
	return v.value
}

func (v *NullableInlineResponse20015Data) Set(val *InlineResponse20015Data) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse20015Data) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse20015Data) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse20015Data(val *InlineResponse20015Data) *NullableInlineResponse20015Data {
	return &NullableInlineResponse20015Data{value: val, isSet: true}
}

func (v NullableInlineResponse20015Data) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse20015Data) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


