/*
 * sdk_api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ContractDataERC721Shop ContractERC721またはContractERC721Shopに必要なデータ
type ContractDataERC721Shop struct {
	ChainType ChainType `json:"chainType"`
	NetworkId NetworkId `json:"networkId"`
	ContractAddress string `json:"contractAddress"`
	// JSON.stringifyしたもの
	Abi string `json:"abi"`
}

// NewContractDataERC721Shop instantiates a new ContractDataERC721Shop object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContractDataERC721Shop(chainType ChainType, networkId NetworkId, contractAddress string, abi string) *ContractDataERC721Shop {
	this := ContractDataERC721Shop{}
	this.ChainType = chainType
	this.NetworkId = networkId
	this.ContractAddress = contractAddress
	this.Abi = abi
	return &this
}

// NewContractDataERC721ShopWithDefaults instantiates a new ContractDataERC721Shop object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContractDataERC721ShopWithDefaults() *ContractDataERC721Shop {
	this := ContractDataERC721Shop{}
	return &this
}

// GetChainType returns the ChainType field value
func (o *ContractDataERC721Shop) GetChainType() ChainType {
	if o == nil {
		var ret ChainType
		return ret
	}

	return o.ChainType
}

// GetChainTypeOk returns a tuple with the ChainType field value
// and a boolean to check if the value has been set.
func (o *ContractDataERC721Shop) GetChainTypeOk() (*ChainType, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ChainType, true
}

// SetChainType sets field value
func (o *ContractDataERC721Shop) SetChainType(v ChainType) {
	o.ChainType = v
}

// GetNetworkId returns the NetworkId field value
func (o *ContractDataERC721Shop) GetNetworkId() NetworkId {
	if o == nil {
		var ret NetworkId
		return ret
	}

	return o.NetworkId
}

// GetNetworkIdOk returns a tuple with the NetworkId field value
// and a boolean to check if the value has been set.
func (o *ContractDataERC721Shop) GetNetworkIdOk() (*NetworkId, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.NetworkId, true
}

// SetNetworkId sets field value
func (o *ContractDataERC721Shop) SetNetworkId(v NetworkId) {
	o.NetworkId = v
}

// GetContractAddress returns the ContractAddress field value
func (o *ContractDataERC721Shop) GetContractAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContractAddress
}

// GetContractAddressOk returns a tuple with the ContractAddress field value
// and a boolean to check if the value has been set.
func (o *ContractDataERC721Shop) GetContractAddressOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ContractAddress, true
}

// SetContractAddress sets field value
func (o *ContractDataERC721Shop) SetContractAddress(v string) {
	o.ContractAddress = v
}

// GetAbi returns the Abi field value
func (o *ContractDataERC721Shop) GetAbi() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Abi
}

// GetAbiOk returns a tuple with the Abi field value
// and a boolean to check if the value has been set.
func (o *ContractDataERC721Shop) GetAbiOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Abi, true
}

// SetAbi sets field value
func (o *ContractDataERC721Shop) SetAbi(v string) {
	o.Abi = v
}

func (o ContractDataERC721Shop) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["chainType"] = o.ChainType
	}
	if true {
		toSerialize["networkId"] = o.NetworkId
	}
	if true {
		toSerialize["contractAddress"] = o.ContractAddress
	}
	if true {
		toSerialize["abi"] = o.Abi
	}
	return json.Marshal(toSerialize)
}

type NullableContractDataERC721Shop struct {
	value *ContractDataERC721Shop
	isSet bool
}

func (v NullableContractDataERC721Shop) Get() *ContractDataERC721Shop {
	return v.value
}

func (v *NullableContractDataERC721Shop) Set(val *ContractDataERC721Shop) {
	v.value = val
	v.isSet = true
}

func (v NullableContractDataERC721Shop) IsSet() bool {
	return v.isSet
}

func (v *NullableContractDataERC721Shop) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContractDataERC721Shop(val *ContractDataERC721Shop) *NullableContractDataERC721Shop {
	return &NullableContractDataERC721Shop{value: val, isSet: true}
}

func (v NullableContractDataERC721Shop) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContractDataERC721Shop) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


