/*
sdk_api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreateOrUpdateItemStockPhysicalShippingInfo200Response struct for CreateOrUpdateItemStockPhysicalShippingInfo200Response
type CreateOrUpdateItemStockPhysicalShippingInfo200Response struct {
	Data string `json:"data"`
	Meta map[string]interface{} `json:"meta"`
}

// NewCreateOrUpdateItemStockPhysicalShippingInfo200Response instantiates a new CreateOrUpdateItemStockPhysicalShippingInfo200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrUpdateItemStockPhysicalShippingInfo200Response(data string, meta map[string]interface{}) *CreateOrUpdateItemStockPhysicalShippingInfo200Response {
	this := CreateOrUpdateItemStockPhysicalShippingInfo200Response{}
	this.Data = data
	this.Meta = meta
	return &this
}

// NewCreateOrUpdateItemStockPhysicalShippingInfo200ResponseWithDefaults instantiates a new CreateOrUpdateItemStockPhysicalShippingInfo200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrUpdateItemStockPhysicalShippingInfo200ResponseWithDefaults() *CreateOrUpdateItemStockPhysicalShippingInfo200Response {
	this := CreateOrUpdateItemStockPhysicalShippingInfo200Response{}
	return &this
}

// GetData returns the Data field value
func (o *CreateOrUpdateItemStockPhysicalShippingInfo200Response) GetData() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateOrUpdateItemStockPhysicalShippingInfo200Response) GetDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreateOrUpdateItemStockPhysicalShippingInfo200Response) SetData(v string) {
	o.Data = v
}

// GetMeta returns the Meta field value
func (o *CreateOrUpdateItemStockPhysicalShippingInfo200Response) GetMeta() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *CreateOrUpdateItemStockPhysicalShippingInfo200Response) GetMetaOk() (map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Meta, true
}

// SetMeta sets field value
func (o *CreateOrUpdateItemStockPhysicalShippingInfo200Response) SetMeta(v map[string]interface{}) {
	o.Meta = v
}

func (o CreateOrUpdateItemStockPhysicalShippingInfo200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	if true {
		toSerialize["meta"] = o.Meta
	}
	return json.Marshal(toSerialize)
}

type NullableCreateOrUpdateItemStockPhysicalShippingInfo200Response struct {
	value *CreateOrUpdateItemStockPhysicalShippingInfo200Response
	isSet bool
}

func (v NullableCreateOrUpdateItemStockPhysicalShippingInfo200Response) Get() *CreateOrUpdateItemStockPhysicalShippingInfo200Response {
	return v.value
}

func (v *NullableCreateOrUpdateItemStockPhysicalShippingInfo200Response) Set(val *CreateOrUpdateItemStockPhysicalShippingInfo200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrUpdateItemStockPhysicalShippingInfo200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrUpdateItemStockPhysicalShippingInfo200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrUpdateItemStockPhysicalShippingInfo200Response(val *CreateOrUpdateItemStockPhysicalShippingInfo200Response) *NullableCreateOrUpdateItemStockPhysicalShippingInfo200Response {
	return &NullableCreateOrUpdateItemStockPhysicalShippingInfo200Response{value: val, isSet: true}
}

func (v NullableCreateOrUpdateItemStockPhysicalShippingInfo200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrUpdateItemStockPhysicalShippingInfo200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


