/*
sdk_api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetBiddedItemStocksByWalletAddress200Response struct for GetBiddedItemStocksByWalletAddress200Response
type GetBiddedItemStocksByWalletAddress200Response struct {
	Data []ItemStock `json:"data"`
	Meta map[string]interface{} `json:"meta"`
}

// NewGetBiddedItemStocksByWalletAddress200Response instantiates a new GetBiddedItemStocksByWalletAddress200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetBiddedItemStocksByWalletAddress200Response(data []ItemStock, meta map[string]interface{}) *GetBiddedItemStocksByWalletAddress200Response {
	this := GetBiddedItemStocksByWalletAddress200Response{}
	this.Data = data
	this.Meta = meta
	return &this
}

// NewGetBiddedItemStocksByWalletAddress200ResponseWithDefaults instantiates a new GetBiddedItemStocksByWalletAddress200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetBiddedItemStocksByWalletAddress200ResponseWithDefaults() *GetBiddedItemStocksByWalletAddress200Response {
	this := GetBiddedItemStocksByWalletAddress200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetBiddedItemStocksByWalletAddress200Response) GetData() []ItemStock {
	if o == nil {
		var ret []ItemStock
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetBiddedItemStocksByWalletAddress200Response) GetDataOk() ([]ItemStock, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GetBiddedItemStocksByWalletAddress200Response) SetData(v []ItemStock) {
	o.Data = v
}

// GetMeta returns the Meta field value
func (o *GetBiddedItemStocksByWalletAddress200Response) GetMeta() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *GetBiddedItemStocksByWalletAddress200Response) GetMetaOk() (map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Meta, true
}

// SetMeta sets field value
func (o *GetBiddedItemStocksByWalletAddress200Response) SetMeta(v map[string]interface{}) {
	o.Meta = v
}

func (o GetBiddedItemStocksByWalletAddress200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	if true {
		toSerialize["meta"] = o.Meta
	}
	return json.Marshal(toSerialize)
}

type NullableGetBiddedItemStocksByWalletAddress200Response struct {
	value *GetBiddedItemStocksByWalletAddress200Response
	isSet bool
}

func (v NullableGetBiddedItemStocksByWalletAddress200Response) Get() *GetBiddedItemStocksByWalletAddress200Response {
	return v.value
}

func (v *NullableGetBiddedItemStocksByWalletAddress200Response) Set(val *GetBiddedItemStocksByWalletAddress200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetBiddedItemStocksByWalletAddress200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetBiddedItemStocksByWalletAddress200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetBiddedItemStocksByWalletAddress200Response(val *GetBiddedItemStocksByWalletAddress200Response) *NullableGetBiddedItemStocksByWalletAddress200Response {
	return &NullableGetBiddedItemStocksByWalletAddress200Response{value: val, isSet: true}
}

func (v NullableGetBiddedItemStocksByWalletAddress200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetBiddedItemStocksByWalletAddress200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


