/*
 * sdk_api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InlineResponse20017Data struct for InlineResponse20017Data
type InlineResponse20017Data struct {
	ImageId string `json:"imageId"`
	UploadSignedUrl string `json:"uploadSignedUrl"`
	ReadSignedUrl string `json:"readSignedUrl"`
}

// NewInlineResponse20017Data instantiates a new InlineResponse20017Data object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse20017Data(imageId string, uploadSignedUrl string, readSignedUrl string) *InlineResponse20017Data {
	this := InlineResponse20017Data{}
	this.ImageId = imageId
	this.UploadSignedUrl = uploadSignedUrl
	this.ReadSignedUrl = readSignedUrl
	return &this
}

// NewInlineResponse20017DataWithDefaults instantiates a new InlineResponse20017Data object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse20017DataWithDefaults() *InlineResponse20017Data {
	this := InlineResponse20017Data{}
	return &this
}

// GetImageId returns the ImageId field value
func (o *InlineResponse20017Data) GetImageId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ImageId
}

// GetImageIdOk returns a tuple with the ImageId field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20017Data) GetImageIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ImageId, true
}

// SetImageId sets field value
func (o *InlineResponse20017Data) SetImageId(v string) {
	o.ImageId = v
}

// GetUploadSignedUrl returns the UploadSignedUrl field value
func (o *InlineResponse20017Data) GetUploadSignedUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UploadSignedUrl
}

// GetUploadSignedUrlOk returns a tuple with the UploadSignedUrl field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20017Data) GetUploadSignedUrlOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.UploadSignedUrl, true
}

// SetUploadSignedUrl sets field value
func (o *InlineResponse20017Data) SetUploadSignedUrl(v string) {
	o.UploadSignedUrl = v
}

// GetReadSignedUrl returns the ReadSignedUrl field value
func (o *InlineResponse20017Data) GetReadSignedUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReadSignedUrl
}

// GetReadSignedUrlOk returns a tuple with the ReadSignedUrl field value
// and a boolean to check if the value has been set.
func (o *InlineResponse20017Data) GetReadSignedUrlOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ReadSignedUrl, true
}

// SetReadSignedUrl sets field value
func (o *InlineResponse20017Data) SetReadSignedUrl(v string) {
	o.ReadSignedUrl = v
}

func (o InlineResponse20017Data) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["imageId"] = o.ImageId
	}
	if true {
		toSerialize["uploadSignedUrl"] = o.UploadSignedUrl
	}
	if true {
		toSerialize["readSignedUrl"] = o.ReadSignedUrl
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse20017Data struct {
	value *InlineResponse20017Data
	isSet bool
}

func (v NullableInlineResponse20017Data) Get() *InlineResponse20017Data {
	return v.value
}

func (v *NullableInlineResponse20017Data) Set(val *InlineResponse20017Data) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse20017Data) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse20017Data) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse20017Data(val *InlineResponse20017Data) *NullableInlineResponse20017Data {
	return &NullableInlineResponse20017Data{value: val, isSet: true}
}

func (v NullableInlineResponse20017Data) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse20017Data) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


