/*
 * sdk_api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InlineResponse2003Data struct for InlineResponse2003Data
type InlineResponse2003Data struct {
	Signature string `json:"signature"`
	// 対応したコントラクトのメソッドに渡す
	ContractMethodArg []AnyOfstringnumberintegerbooleanarrayobject `json:"contractMethodArg"`
}

// NewInlineResponse2003Data instantiates a new InlineResponse2003Data object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse2003Data(signature string, contractMethodArg []AnyOfstringnumberintegerbooleanarrayobject) *InlineResponse2003Data {
	this := InlineResponse2003Data{}
	this.Signature = signature
	this.ContractMethodArg = contractMethodArg
	return &this
}

// NewInlineResponse2003DataWithDefaults instantiates a new InlineResponse2003Data object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse2003DataWithDefaults() *InlineResponse2003Data {
	this := InlineResponse2003Data{}
	return &this
}

// GetSignature returns the Signature field value
func (o *InlineResponse2003Data) GetSignature() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2003Data) GetSignatureOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Signature, true
}

// SetSignature sets field value
func (o *InlineResponse2003Data) SetSignature(v string) {
	o.Signature = v
}

// GetContractMethodArg returns the ContractMethodArg field value
func (o *InlineResponse2003Data) GetContractMethodArg() []AnyOfstringnumberintegerbooleanarrayobject {
	if o == nil {
		var ret []AnyOfstringnumberintegerbooleanarrayobject
		return ret
	}

	return o.ContractMethodArg
}

// GetContractMethodArgOk returns a tuple with the ContractMethodArg field value
// and a boolean to check if the value has been set.
func (o *InlineResponse2003Data) GetContractMethodArgOk() (*[]AnyOfstringnumberintegerbooleanarrayobject, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ContractMethodArg, true
}

// SetContractMethodArg sets field value
func (o *InlineResponse2003Data) SetContractMethodArg(v []AnyOfstringnumberintegerbooleanarrayobject) {
	o.ContractMethodArg = v
}

func (o InlineResponse2003Data) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["signature"] = o.Signature
	}
	if true {
		toSerialize["contractMethodArg"] = o.ContractMethodArg
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse2003Data struct {
	value *InlineResponse2003Data
	isSet bool
}

func (v NullableInlineResponse2003Data) Get() *InlineResponse2003Data {
	return v.value
}

func (v *NullableInlineResponse2003Data) Set(val *InlineResponse2003Data) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse2003Data) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse2003Data) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse2003Data(val *InlineResponse2003Data) *NullableInlineResponse2003Data {
	return &NullableInlineResponse2003Data{value: val, isSet: true}
}

func (v NullableInlineResponse2003Data) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse2003Data) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


