/*
sdk_api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// WalletAddressProfile struct for WalletAddressProfile
type WalletAddressProfile struct {
	WalletAddress string `json:"walletAddress"`
	AvatarImageId string `json:"avatarImageId"`
	DisplayName string `json:"displayName"`
	Bio string `json:"bio"`
	TwitterAccountName string `json:"twitterAccountName"`
	InstagramAccountName string `json:"instagramAccountName"`
	HomepageUrl string `json:"homepageUrl"`
}

// NewWalletAddressProfile instantiates a new WalletAddressProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWalletAddressProfile(walletAddress string, avatarImageId string, displayName string, bio string, twitterAccountName string, instagramAccountName string, homepageUrl string) *WalletAddressProfile {
	this := WalletAddressProfile{}
	this.WalletAddress = walletAddress
	this.AvatarImageId = avatarImageId
	this.DisplayName = displayName
	this.Bio = bio
	this.TwitterAccountName = twitterAccountName
	this.InstagramAccountName = instagramAccountName
	this.HomepageUrl = homepageUrl
	return &this
}

// NewWalletAddressProfileWithDefaults instantiates a new WalletAddressProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWalletAddressProfileWithDefaults() *WalletAddressProfile {
	this := WalletAddressProfile{}
	return &this
}

// GetWalletAddress returns the WalletAddress field value
func (o *WalletAddressProfile) GetWalletAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WalletAddress
}

// GetWalletAddressOk returns a tuple with the WalletAddress field value
// and a boolean to check if the value has been set.
func (o *WalletAddressProfile) GetWalletAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WalletAddress, true
}

// SetWalletAddress sets field value
func (o *WalletAddressProfile) SetWalletAddress(v string) {
	o.WalletAddress = v
}

// GetAvatarImageId returns the AvatarImageId field value
func (o *WalletAddressProfile) GetAvatarImageId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AvatarImageId
}

// GetAvatarImageIdOk returns a tuple with the AvatarImageId field value
// and a boolean to check if the value has been set.
func (o *WalletAddressProfile) GetAvatarImageIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AvatarImageId, true
}

// SetAvatarImageId sets field value
func (o *WalletAddressProfile) SetAvatarImageId(v string) {
	o.AvatarImageId = v
}

// GetDisplayName returns the DisplayName field value
func (o *WalletAddressProfile) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *WalletAddressProfile) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *WalletAddressProfile) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetBio returns the Bio field value
func (o *WalletAddressProfile) GetBio() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Bio
}

// GetBioOk returns a tuple with the Bio field value
// and a boolean to check if the value has been set.
func (o *WalletAddressProfile) GetBioOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Bio, true
}

// SetBio sets field value
func (o *WalletAddressProfile) SetBio(v string) {
	o.Bio = v
}

// GetTwitterAccountName returns the TwitterAccountName field value
func (o *WalletAddressProfile) GetTwitterAccountName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TwitterAccountName
}

// GetTwitterAccountNameOk returns a tuple with the TwitterAccountName field value
// and a boolean to check if the value has been set.
func (o *WalletAddressProfile) GetTwitterAccountNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TwitterAccountName, true
}

// SetTwitterAccountName sets field value
func (o *WalletAddressProfile) SetTwitterAccountName(v string) {
	o.TwitterAccountName = v
}

// GetInstagramAccountName returns the InstagramAccountName field value
func (o *WalletAddressProfile) GetInstagramAccountName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InstagramAccountName
}

// GetInstagramAccountNameOk returns a tuple with the InstagramAccountName field value
// and a boolean to check if the value has been set.
func (o *WalletAddressProfile) GetInstagramAccountNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstagramAccountName, true
}

// SetInstagramAccountName sets field value
func (o *WalletAddressProfile) SetInstagramAccountName(v string) {
	o.InstagramAccountName = v
}

// GetHomepageUrl returns the HomepageUrl field value
func (o *WalletAddressProfile) GetHomepageUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HomepageUrl
}

// GetHomepageUrlOk returns a tuple with the HomepageUrl field value
// and a boolean to check if the value has been set.
func (o *WalletAddressProfile) GetHomepageUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HomepageUrl, true
}

// SetHomepageUrl sets field value
func (o *WalletAddressProfile) SetHomepageUrl(v string) {
	o.HomepageUrl = v
}

func (o WalletAddressProfile) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["walletAddress"] = o.WalletAddress
	}
	if true {
		toSerialize["avatarImageId"] = o.AvatarImageId
	}
	if true {
		toSerialize["displayName"] = o.DisplayName
	}
	if true {
		toSerialize["bio"] = o.Bio
	}
	if true {
		toSerialize["twitterAccountName"] = o.TwitterAccountName
	}
	if true {
		toSerialize["instagramAccountName"] = o.InstagramAccountName
	}
	if true {
		toSerialize["homepageUrl"] = o.HomepageUrl
	}
	return json.Marshal(toSerialize)
}

type NullableWalletAddressProfile struct {
	value *WalletAddressProfile
	isSet bool
}

func (v NullableWalletAddressProfile) Get() *WalletAddressProfile {
	return v.value
}

func (v *NullableWalletAddressProfile) Set(val *WalletAddressProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableWalletAddressProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableWalletAddressProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWalletAddressProfile(val *WalletAddressProfile) *NullableWalletAddressProfile {
	return &NullableWalletAddressProfile{value: val, isSet: true}
}

func (v NullableWalletAddressProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWalletAddressProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


