/*
sdk_api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetItems200Response struct for GetItems200Response
type GetItems200Response struct {
	Data []Item `json:"data"`
	Meta map[string]interface{} `json:"meta"`
}

// NewGetItems200Response instantiates a new GetItems200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetItems200Response(data []Item, meta map[string]interface{}) *GetItems200Response {
	this := GetItems200Response{}
	this.Data = data
	this.Meta = meta
	return &this
}

// NewGetItems200ResponseWithDefaults instantiates a new GetItems200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetItems200ResponseWithDefaults() *GetItems200Response {
	this := GetItems200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetItems200Response) GetData() []Item {
	if o == nil {
		var ret []Item
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetItems200Response) GetDataOk() ([]Item, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GetItems200Response) SetData(v []Item) {
	o.Data = v
}

// GetMeta returns the Meta field value
func (o *GetItems200Response) GetMeta() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *GetItems200Response) GetMetaOk() (map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Meta, true
}

// SetMeta sets field value
func (o *GetItems200Response) SetMeta(v map[string]interface{}) {
	o.Meta = v
}

func (o GetItems200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	if true {
		toSerialize["meta"] = o.Meta
	}
	return json.Marshal(toSerialize)
}

type NullableGetItems200Response struct {
	value *GetItems200Response
	isSet bool
}

func (v NullableGetItems200Response) Get() *GetItems200Response {
	return v.value
}

func (v *NullableGetItems200Response) Set(val *GetItems200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetItems200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetItems200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetItems200Response(val *GetItems200Response) *NullableGetItems200Response {
	return &NullableGetItems200Response{value: val, isSet: true}
}

func (v NullableGetItems200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetItems200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


