/*
sdk_api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreateOrUpdateItemStockPhysicalShippingInfoRequestData struct for CreateOrUpdateItemStockPhysicalShippingInfoRequestData
type CreateOrUpdateItemStockPhysicalShippingInfoRequestData struct {
	Domain SignatureDomain `json:"domain"`
	PrimaryType string `json:"primaryType"`
	Message CreateOrUpdateItemStockPhysicalShippingInfoRequestBodyMessage `json:"message"`
	Types map[string]interface{} `json:"types"`
}

// NewCreateOrUpdateItemStockPhysicalShippingInfoRequestData instantiates a new CreateOrUpdateItemStockPhysicalShippingInfoRequestData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrUpdateItemStockPhysicalShippingInfoRequestData(domain SignatureDomain, primaryType string, message CreateOrUpdateItemStockPhysicalShippingInfoRequestBodyMessage, types map[string]interface{}) *CreateOrUpdateItemStockPhysicalShippingInfoRequestData {
	this := CreateOrUpdateItemStockPhysicalShippingInfoRequestData{}
	this.Domain = domain
	this.PrimaryType = primaryType
	this.Message = message
	this.Types = types
	return &this
}

// NewCreateOrUpdateItemStockPhysicalShippingInfoRequestDataWithDefaults instantiates a new CreateOrUpdateItemStockPhysicalShippingInfoRequestData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrUpdateItemStockPhysicalShippingInfoRequestDataWithDefaults() *CreateOrUpdateItemStockPhysicalShippingInfoRequestData {
	this := CreateOrUpdateItemStockPhysicalShippingInfoRequestData{}
	return &this
}

// GetDomain returns the Domain field value
func (o *CreateOrUpdateItemStockPhysicalShippingInfoRequestData) GetDomain() SignatureDomain {
	if o == nil {
		var ret SignatureDomain
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *CreateOrUpdateItemStockPhysicalShippingInfoRequestData) GetDomainOk() (*SignatureDomain, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *CreateOrUpdateItemStockPhysicalShippingInfoRequestData) SetDomain(v SignatureDomain) {
	o.Domain = v
}

// GetPrimaryType returns the PrimaryType field value
func (o *CreateOrUpdateItemStockPhysicalShippingInfoRequestData) GetPrimaryType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PrimaryType
}

// GetPrimaryTypeOk returns a tuple with the PrimaryType field value
// and a boolean to check if the value has been set.
func (o *CreateOrUpdateItemStockPhysicalShippingInfoRequestData) GetPrimaryTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrimaryType, true
}

// SetPrimaryType sets field value
func (o *CreateOrUpdateItemStockPhysicalShippingInfoRequestData) SetPrimaryType(v string) {
	o.PrimaryType = v
}

// GetMessage returns the Message field value
func (o *CreateOrUpdateItemStockPhysicalShippingInfoRequestData) GetMessage() CreateOrUpdateItemStockPhysicalShippingInfoRequestBodyMessage {
	if o == nil {
		var ret CreateOrUpdateItemStockPhysicalShippingInfoRequestBodyMessage
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *CreateOrUpdateItemStockPhysicalShippingInfoRequestData) GetMessageOk() (*CreateOrUpdateItemStockPhysicalShippingInfoRequestBodyMessage, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *CreateOrUpdateItemStockPhysicalShippingInfoRequestData) SetMessage(v CreateOrUpdateItemStockPhysicalShippingInfoRequestBodyMessage) {
	o.Message = v
}

// GetTypes returns the Types field value
func (o *CreateOrUpdateItemStockPhysicalShippingInfoRequestData) GetTypes() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Types
}

// GetTypesOk returns a tuple with the Types field value
// and a boolean to check if the value has been set.
func (o *CreateOrUpdateItemStockPhysicalShippingInfoRequestData) GetTypesOk() (map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Types, true
}

// SetTypes sets field value
func (o *CreateOrUpdateItemStockPhysicalShippingInfoRequestData) SetTypes(v map[string]interface{}) {
	o.Types = v
}

func (o CreateOrUpdateItemStockPhysicalShippingInfoRequestData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["domain"] = o.Domain
	}
	if true {
		toSerialize["primaryType"] = o.PrimaryType
	}
	if true {
		toSerialize["message"] = o.Message
	}
	if true {
		toSerialize["types"] = o.Types
	}
	return json.Marshal(toSerialize)
}

type NullableCreateOrUpdateItemStockPhysicalShippingInfoRequestData struct {
	value *CreateOrUpdateItemStockPhysicalShippingInfoRequestData
	isSet bool
}

func (v NullableCreateOrUpdateItemStockPhysicalShippingInfoRequestData) Get() *CreateOrUpdateItemStockPhysicalShippingInfoRequestData {
	return v.value
}

func (v *NullableCreateOrUpdateItemStockPhysicalShippingInfoRequestData) Set(val *CreateOrUpdateItemStockPhysicalShippingInfoRequestData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrUpdateItemStockPhysicalShippingInfoRequestData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrUpdateItemStockPhysicalShippingInfoRequestData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrUpdateItemStockPhysicalShippingInfoRequestData(val *CreateOrUpdateItemStockPhysicalShippingInfoRequestData) *NullableCreateOrUpdateItemStockPhysicalShippingInfoRequestData {
	return &NullableCreateOrUpdateItemStockPhysicalShippingInfoRequestData{value: val, isSet: true}
}

func (v NullableCreateOrUpdateItemStockPhysicalShippingInfoRequestData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrUpdateItemStockPhysicalShippingInfoRequestData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


