/*
sdk_api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetSellableItemStockERC721Id200Response struct for GetSellableItemStockERC721Id200Response
type GetSellableItemStockERC721Id200Response struct {
	Data GetSellableItemStockERC721Id200ResponseData `json:"data"`
	Meta map[string]interface{} `json:"meta"`
}

// NewGetSellableItemStockERC721Id200Response instantiates a new GetSellableItemStockERC721Id200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSellableItemStockERC721Id200Response(data GetSellableItemStockERC721Id200ResponseData, meta map[string]interface{}) *GetSellableItemStockERC721Id200Response {
	this := GetSellableItemStockERC721Id200Response{}
	this.Data = data
	this.Meta = meta
	return &this
}

// NewGetSellableItemStockERC721Id200ResponseWithDefaults instantiates a new GetSellableItemStockERC721Id200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSellableItemStockERC721Id200ResponseWithDefaults() *GetSellableItemStockERC721Id200Response {
	this := GetSellableItemStockERC721Id200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetSellableItemStockERC721Id200Response) GetData() GetSellableItemStockERC721Id200ResponseData {
	if o == nil {
		var ret GetSellableItemStockERC721Id200ResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetSellableItemStockERC721Id200Response) GetDataOk() (*GetSellableItemStockERC721Id200ResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetSellableItemStockERC721Id200Response) SetData(v GetSellableItemStockERC721Id200ResponseData) {
	o.Data = v
}

// GetMeta returns the Meta field value
func (o *GetSellableItemStockERC721Id200Response) GetMeta() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *GetSellableItemStockERC721Id200Response) GetMetaOk() (map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Meta, true
}

// SetMeta sets field value
func (o *GetSellableItemStockERC721Id200Response) SetMeta(v map[string]interface{}) {
	o.Meta = v
}

func (o GetSellableItemStockERC721Id200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	if true {
		toSerialize["meta"] = o.Meta
	}
	return json.Marshal(toSerialize)
}

type NullableGetSellableItemStockERC721Id200Response struct {
	value *GetSellableItemStockERC721Id200Response
	isSet bool
}

func (v NullableGetSellableItemStockERC721Id200Response) Get() *GetSellableItemStockERC721Id200Response {
	return v.value
}

func (v *NullableGetSellableItemStockERC721Id200Response) Set(val *GetSellableItemStockERC721Id200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSellableItemStockERC721Id200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSellableItemStockERC721Id200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSellableItemStockERC721Id200Response(val *GetSellableItemStockERC721Id200Response) *NullableGetSellableItemStockERC721Id200Response {
	return &NullableGetSellableItemStockERC721Id200Response{value: val, isSet: true}
}

func (v NullableGetSellableItemStockERC721Id200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSellableItemStockERC721Id200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


