/*
sdk_api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetAvatar200Response struct for GetAvatar200Response
type GetAvatar200Response struct {
	Meta map[string]interface{} `json:"meta,omitempty"`
	Data *GetAvatar200ResponseData `json:"data,omitempty"`
}

// NewGetAvatar200Response instantiates a new GetAvatar200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAvatar200Response() *GetAvatar200Response {
	this := GetAvatar200Response{}
	return &this
}

// NewGetAvatar200ResponseWithDefaults instantiates a new GetAvatar200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAvatar200ResponseWithDefaults() *GetAvatar200Response {
	this := GetAvatar200Response{}
	return &this
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *GetAvatar200Response) GetMeta() map[string]interface{} {
	if o == nil || o.Meta == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAvatar200Response) GetMetaOk() (map[string]interface{}, bool) {
	if o == nil || o.Meta == nil {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *GetAvatar200Response) HasMeta() bool {
	if o != nil && o.Meta != nil {
		return true
	}

	return false
}

// SetMeta gets a reference to the given map[string]interface{} and assigns it to the Meta field.
func (o *GetAvatar200Response) SetMeta(v map[string]interface{}) {
	o.Meta = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetAvatar200Response) GetData() GetAvatar200ResponseData {
	if o == nil || o.Data == nil {
		var ret GetAvatar200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAvatar200Response) GetDataOk() (*GetAvatar200ResponseData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetAvatar200Response) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given GetAvatar200ResponseData and assigns it to the Data field.
func (o *GetAvatar200Response) SetData(v GetAvatar200ResponseData) {
	o.Data = &v
}

func (o GetAvatar200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Meta != nil {
		toSerialize["meta"] = o.Meta
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableGetAvatar200Response struct {
	value *GetAvatar200Response
	isSet bool
}

func (v NullableGetAvatar200Response) Get() *GetAvatar200Response {
	return v.value
}

func (v *NullableGetAvatar200Response) Set(val *GetAvatar200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAvatar200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAvatar200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAvatar200Response(val *GetAvatar200Response) *NullableGetAvatar200Response {
	return &NullableGetAvatar200Response{value: val, isSet: true}
}

func (v NullableGetAvatar200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAvatar200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


