/*
sdk_api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreateStripePaymentIntentRequest struct for CreateStripePaymentIntentRequest
type CreateStripePaymentIntentRequest struct {
	// Item id that will be purchased
	ItemId string `json:"itemId"`
	// Buyer wallet address
	ToAddress string `json:"toAddress"`
	UserResidence UserResidence `json:"userResidence"`
}

// NewCreateStripePaymentIntentRequest instantiates a new CreateStripePaymentIntentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateStripePaymentIntentRequest(itemId string, toAddress string, userResidence UserResidence) *CreateStripePaymentIntentRequest {
	this := CreateStripePaymentIntentRequest{}
	this.ItemId = itemId
	this.ToAddress = toAddress
	this.UserResidence = userResidence
	return &this
}

// NewCreateStripePaymentIntentRequestWithDefaults instantiates a new CreateStripePaymentIntentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateStripePaymentIntentRequestWithDefaults() *CreateStripePaymentIntentRequest {
	this := CreateStripePaymentIntentRequest{}
	return &this
}

// GetItemId returns the ItemId field value
func (o *CreateStripePaymentIntentRequest) GetItemId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ItemId
}

// GetItemIdOk returns a tuple with the ItemId field value
// and a boolean to check if the value has been set.
func (o *CreateStripePaymentIntentRequest) GetItemIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ItemId, true
}

// SetItemId sets field value
func (o *CreateStripePaymentIntentRequest) SetItemId(v string) {
	o.ItemId = v
}

// GetToAddress returns the ToAddress field value
func (o *CreateStripePaymentIntentRequest) GetToAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ToAddress
}

// GetToAddressOk returns a tuple with the ToAddress field value
// and a boolean to check if the value has been set.
func (o *CreateStripePaymentIntentRequest) GetToAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ToAddress, true
}

// SetToAddress sets field value
func (o *CreateStripePaymentIntentRequest) SetToAddress(v string) {
	o.ToAddress = v
}

// GetUserResidence returns the UserResidence field value
func (o *CreateStripePaymentIntentRequest) GetUserResidence() UserResidence {
	if o == nil {
		var ret UserResidence
		return ret
	}

	return o.UserResidence
}

// GetUserResidenceOk returns a tuple with the UserResidence field value
// and a boolean to check if the value has been set.
func (o *CreateStripePaymentIntentRequest) GetUserResidenceOk() (*UserResidence, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserResidence, true
}

// SetUserResidence sets field value
func (o *CreateStripePaymentIntentRequest) SetUserResidence(v UserResidence) {
	o.UserResidence = v
}

func (o CreateStripePaymentIntentRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["itemId"] = o.ItemId
	}
	if true {
		toSerialize["toAddress"] = o.ToAddress
	}
	if true {
		toSerialize["userResidence"] = o.UserResidence
	}
	return json.Marshal(toSerialize)
}

type NullableCreateStripePaymentIntentRequest struct {
	value *CreateStripePaymentIntentRequest
	isSet bool
}

func (v NullableCreateStripePaymentIntentRequest) Get() *CreateStripePaymentIntentRequest {
	return v.value
}

func (v *NullableCreateStripePaymentIntentRequest) Set(val *CreateStripePaymentIntentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateStripePaymentIntentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateStripePaymentIntentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateStripePaymentIntentRequest(val *CreateStripePaymentIntentRequest) *NullableCreateStripePaymentIntentRequest {
	return &NullableCreateStripePaymentIntentRequest{value: val, isSet: true}
}

func (v NullableCreateStripePaymentIntentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateStripePaymentIntentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


