/*
 * sdk_api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetPaymentIntentByIdResponseBodyData struct for GetPaymentIntentByIdResponseBodyData
type GetPaymentIntentByIdResponseBodyData struct {
	CryptoPaymentIntentId string `json:"cryptoPaymentIntentId"`
	ContractMethodResource GetPaymentIntentByIdResponseBodyDataContractMethodResource `json:"contractMethodResource"`
}

// NewGetPaymentIntentByIdResponseBodyData instantiates a new GetPaymentIntentByIdResponseBodyData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPaymentIntentByIdResponseBodyData(cryptoPaymentIntentId string, contractMethodResource GetPaymentIntentByIdResponseBodyDataContractMethodResource) *GetPaymentIntentByIdResponseBodyData {
	this := GetPaymentIntentByIdResponseBodyData{}
	this.CryptoPaymentIntentId = cryptoPaymentIntentId
	this.ContractMethodResource = contractMethodResource
	return &this
}

// NewGetPaymentIntentByIdResponseBodyDataWithDefaults instantiates a new GetPaymentIntentByIdResponseBodyData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPaymentIntentByIdResponseBodyDataWithDefaults() *GetPaymentIntentByIdResponseBodyData {
	this := GetPaymentIntentByIdResponseBodyData{}
	return &this
}

// GetCryptoPaymentIntentId returns the CryptoPaymentIntentId field value
func (o *GetPaymentIntentByIdResponseBodyData) GetCryptoPaymentIntentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CryptoPaymentIntentId
}

// GetCryptoPaymentIntentIdOk returns a tuple with the CryptoPaymentIntentId field value
// and a boolean to check if the value has been set.
func (o *GetPaymentIntentByIdResponseBodyData) GetCryptoPaymentIntentIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CryptoPaymentIntentId, true
}

// SetCryptoPaymentIntentId sets field value
func (o *GetPaymentIntentByIdResponseBodyData) SetCryptoPaymentIntentId(v string) {
	o.CryptoPaymentIntentId = v
}

// GetContractMethodResource returns the ContractMethodResource field value
func (o *GetPaymentIntentByIdResponseBodyData) GetContractMethodResource() GetPaymentIntentByIdResponseBodyDataContractMethodResource {
	if o == nil {
		var ret GetPaymentIntentByIdResponseBodyDataContractMethodResource
		return ret
	}

	return o.ContractMethodResource
}

// GetContractMethodResourceOk returns a tuple with the ContractMethodResource field value
// and a boolean to check if the value has been set.
func (o *GetPaymentIntentByIdResponseBodyData) GetContractMethodResourceOk() (*GetPaymentIntentByIdResponseBodyDataContractMethodResource, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ContractMethodResource, true
}

// SetContractMethodResource sets field value
func (o *GetPaymentIntentByIdResponseBodyData) SetContractMethodResource(v GetPaymentIntentByIdResponseBodyDataContractMethodResource) {
	o.ContractMethodResource = v
}

func (o GetPaymentIntentByIdResponseBodyData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["cryptoPaymentIntentId"] = o.CryptoPaymentIntentId
	}
	if true {
		toSerialize["contractMethodResource"] = o.ContractMethodResource
	}
	return json.Marshal(toSerialize)
}

type NullableGetPaymentIntentByIdResponseBodyData struct {
	value *GetPaymentIntentByIdResponseBodyData
	isSet bool
}

func (v NullableGetPaymentIntentByIdResponseBodyData) Get() *GetPaymentIntentByIdResponseBodyData {
	return v.value
}

func (v *NullableGetPaymentIntentByIdResponseBodyData) Set(val *GetPaymentIntentByIdResponseBodyData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPaymentIntentByIdResponseBodyData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPaymentIntentByIdResponseBodyData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPaymentIntentByIdResponseBodyData(val *GetPaymentIntentByIdResponseBodyData) *NullableGetPaymentIntentByIdResponseBodyData {
	return &NullableGetPaymentIntentByIdResponseBodyData{value: val, isSet: true}
}

func (v NullableGetPaymentIntentByIdResponseBodyData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPaymentIntentByIdResponseBodyData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


