/*
sdk_api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetTokenERC721sByWalletAddress200Response struct for GetTokenERC721sByWalletAddress200Response
type GetTokenERC721sByWalletAddress200Response struct {
	Data []TokenERC721 `json:"data"`
	Meta map[string]interface{} `json:"meta"`
}

// NewGetTokenERC721sByWalletAddress200Response instantiates a new GetTokenERC721sByWalletAddress200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTokenERC721sByWalletAddress200Response(data []TokenERC721, meta map[string]interface{}) *GetTokenERC721sByWalletAddress200Response {
	this := GetTokenERC721sByWalletAddress200Response{}
	this.Data = data
	this.Meta = meta
	return &this
}

// NewGetTokenERC721sByWalletAddress200ResponseWithDefaults instantiates a new GetTokenERC721sByWalletAddress200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTokenERC721sByWalletAddress200ResponseWithDefaults() *GetTokenERC721sByWalletAddress200Response {
	this := GetTokenERC721sByWalletAddress200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetTokenERC721sByWalletAddress200Response) GetData() []TokenERC721 {
	if o == nil {
		var ret []TokenERC721
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetTokenERC721sByWalletAddress200Response) GetDataOk() ([]TokenERC721, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GetTokenERC721sByWalletAddress200Response) SetData(v []TokenERC721) {
	o.Data = v
}

// GetMeta returns the Meta field value
func (o *GetTokenERC721sByWalletAddress200Response) GetMeta() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *GetTokenERC721sByWalletAddress200Response) GetMetaOk() (map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Meta, true
}

// SetMeta sets field value
func (o *GetTokenERC721sByWalletAddress200Response) SetMeta(v map[string]interface{}) {
	o.Meta = v
}

func (o GetTokenERC721sByWalletAddress200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	if true {
		toSerialize["meta"] = o.Meta
	}
	return json.Marshal(toSerialize)
}

type NullableGetTokenERC721sByWalletAddress200Response struct {
	value *GetTokenERC721sByWalletAddress200Response
	isSet bool
}

func (v NullableGetTokenERC721sByWalletAddress200Response) Get() *GetTokenERC721sByWalletAddress200Response {
	return v.value
}

func (v *NullableGetTokenERC721sByWalletAddress200Response) Set(val *GetTokenERC721sByWalletAddress200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTokenERC721sByWalletAddress200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTokenERC721sByWalletAddress200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTokenERC721sByWalletAddress200Response(val *GetTokenERC721sByWalletAddress200Response) *NullableGetTokenERC721sByWalletAddress200Response {
	return &NullableGetTokenERC721sByWalletAddress200Response{value: val, isSet: true}
}

func (v NullableGetTokenERC721sByWalletAddress200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTokenERC721sByWalletAddress200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


