/*
sdk_api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage struct for GetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage
type GetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage struct {
	WalletAddress *string `json:"walletAddress,omitempty"`
	RequestTimestamp *string `json:"requestTimestamp,omitempty"`
}

// NewGetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage instantiates a new GetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage() *GetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage {
	this := GetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage{}
	return &this
}

// NewGetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessageWithDefaults instantiates a new GetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessageWithDefaults() *GetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage {
	this := GetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage{}
	return &this
}

// GetWalletAddress returns the WalletAddress field value if set, zero value otherwise.
func (o *GetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage) GetWalletAddress() string {
	if o == nil || o.WalletAddress == nil {
		var ret string
		return ret
	}
	return *o.WalletAddress
}

// GetWalletAddressOk returns a tuple with the WalletAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage) GetWalletAddressOk() (*string, bool) {
	if o == nil || o.WalletAddress == nil {
		return nil, false
	}
	return o.WalletAddress, true
}

// HasWalletAddress returns a boolean if a field has been set.
func (o *GetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage) HasWalletAddress() bool {
	if o != nil && o.WalletAddress != nil {
		return true
	}

	return false
}

// SetWalletAddress gets a reference to the given string and assigns it to the WalletAddress field.
func (o *GetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage) SetWalletAddress(v string) {
	o.WalletAddress = &v
}

// GetRequestTimestamp returns the RequestTimestamp field value if set, zero value otherwise.
func (o *GetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage) GetRequestTimestamp() string {
	if o == nil || o.RequestTimestamp == nil {
		var ret string
		return ret
	}
	return *o.RequestTimestamp
}

// GetRequestTimestampOk returns a tuple with the RequestTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage) GetRequestTimestampOk() (*string, bool) {
	if o == nil || o.RequestTimestamp == nil {
		return nil, false
	}
	return o.RequestTimestamp, true
}

// HasRequestTimestamp returns a boolean if a field has been set.
func (o *GetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage) HasRequestTimestamp() bool {
	if o != nil && o.RequestTimestamp != nil {
		return true
	}

	return false
}

// SetRequestTimestamp gets a reference to the given string and assigns it to the RequestTimestamp field.
func (o *GetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage) SetRequestTimestamp(v string) {
	o.RequestTimestamp = &v
}

func (o GetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.WalletAddress != nil {
		toSerialize["walletAddress"] = o.WalletAddress
	}
	if o.RequestTimestamp != nil {
		toSerialize["requestTimestamp"] = o.RequestTimestamp
	}
	return json.Marshal(toSerialize)
}

type NullableGetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage struct {
	value *GetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage
	isSet bool
}

func (v NullableGetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage) Get() *GetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage {
	return v.value
}

func (v *NullableGetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage) Set(val *GetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableGetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableGetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage(val *GetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage) *NullableGetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage {
	return &NullableGetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage{value: val, isSet: true}
}

func (v NullableGetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


