/*
sdk_api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetSignByItemStockId200Response struct for GetSignByItemStockId200Response
type GetSignByItemStockId200Response struct {
	Data GetSignByItemStockId200ResponseData `json:"data"`
	Meta map[string]interface{} `json:"meta"`
}

// NewGetSignByItemStockId200Response instantiates a new GetSignByItemStockId200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSignByItemStockId200Response(data GetSignByItemStockId200ResponseData, meta map[string]interface{}) *GetSignByItemStockId200Response {
	this := GetSignByItemStockId200Response{}
	this.Data = data
	this.Meta = meta
	return &this
}

// NewGetSignByItemStockId200ResponseWithDefaults instantiates a new GetSignByItemStockId200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSignByItemStockId200ResponseWithDefaults() *GetSignByItemStockId200Response {
	this := GetSignByItemStockId200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetSignByItemStockId200Response) GetData() GetSignByItemStockId200ResponseData {
	if o == nil {
		var ret GetSignByItemStockId200ResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetSignByItemStockId200Response) GetDataOk() (*GetSignByItemStockId200ResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetSignByItemStockId200Response) SetData(v GetSignByItemStockId200ResponseData) {
	o.Data = v
}

// GetMeta returns the Meta field value
func (o *GetSignByItemStockId200Response) GetMeta() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *GetSignByItemStockId200Response) GetMetaOk() (map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Meta, true
}

// SetMeta sets field value
func (o *GetSignByItemStockId200Response) SetMeta(v map[string]interface{}) {
	o.Meta = v
}

func (o GetSignByItemStockId200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	if true {
		toSerialize["meta"] = o.Meta
	}
	return json.Marshal(toSerialize)
}

type NullableGetSignByItemStockId200Response struct {
	value *GetSignByItemStockId200Response
	isSet bool
}

func (v NullableGetSignByItemStockId200Response) Get() *GetSignByItemStockId200Response {
	return v.value
}

func (v *NullableGetSignByItemStockId200Response) Set(val *GetSignByItemStockId200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSignByItemStockId200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSignByItemStockId200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSignByItemStockId200Response(val *GetSignByItemStockId200Response) *NullableGetSignByItemStockId200Response {
	return &NullableGetSignByItemStockId200Response{value: val, isSet: true}
}

func (v NullableGetSignByItemStockId200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSignByItemStockId200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


