/*
sdk_api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreateStripePaymentIntent200Response struct for CreateStripePaymentIntent200Response
type CreateStripePaymentIntent200Response struct {
	// クライアント側でloadStripeに対して渡す公開可能なAPI-Key
	PublishableKey string `json:"publishableKey"`
	// StripeのPaymentIntentのClientSecret
	Secret string `json:"secret"`
}

// NewCreateStripePaymentIntent200Response instantiates a new CreateStripePaymentIntent200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateStripePaymentIntent200Response(publishableKey string, secret string) *CreateStripePaymentIntent200Response {
	this := CreateStripePaymentIntent200Response{}
	this.PublishableKey = publishableKey
	this.Secret = secret
	return &this
}

// NewCreateStripePaymentIntent200ResponseWithDefaults instantiates a new CreateStripePaymentIntent200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateStripePaymentIntent200ResponseWithDefaults() *CreateStripePaymentIntent200Response {
	this := CreateStripePaymentIntent200Response{}
	return &this
}

// GetPublishableKey returns the PublishableKey field value
func (o *CreateStripePaymentIntent200Response) GetPublishableKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PublishableKey
}

// GetPublishableKeyOk returns a tuple with the PublishableKey field value
// and a boolean to check if the value has been set.
func (o *CreateStripePaymentIntent200Response) GetPublishableKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PublishableKey, true
}

// SetPublishableKey sets field value
func (o *CreateStripePaymentIntent200Response) SetPublishableKey(v string) {
	o.PublishableKey = v
}

// GetSecret returns the Secret field value
func (o *CreateStripePaymentIntent200Response) GetSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Secret
}

// GetSecretOk returns a tuple with the Secret field value
// and a boolean to check if the value has been set.
func (o *CreateStripePaymentIntent200Response) GetSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Secret, true
}

// SetSecret sets field value
func (o *CreateStripePaymentIntent200Response) SetSecret(v string) {
	o.Secret = v
}

func (o CreateStripePaymentIntent200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["publishableKey"] = o.PublishableKey
	}
	if true {
		toSerialize["secret"] = o.Secret
	}
	return json.Marshal(toSerialize)
}

type NullableCreateStripePaymentIntent200Response struct {
	value *CreateStripePaymentIntent200Response
	isSet bool
}

func (v NullableCreateStripePaymentIntent200Response) Get() *CreateStripePaymentIntent200Response {
	return v.value
}

func (v *NullableCreateStripePaymentIntent200Response) Set(val *CreateStripePaymentIntent200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateStripePaymentIntent200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateStripePaymentIntent200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateStripePaymentIntent200Response(val *CreateStripePaymentIntent200Response) *NullableCreateStripePaymentIntent200Response {
	return &NullableCreateStripePaymentIntent200Response{value: val, isSet: true}
}

func (v NullableCreateStripePaymentIntent200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateStripePaymentIntent200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


