/*
sdk_api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetProfile200Response struct for GetProfile200Response
type GetProfile200Response struct {
	Data NullableGetProfile200ResponseData `json:"data"`
	Meta map[string]interface{} `json:"meta"`
}

// NewGetProfile200Response instantiates a new GetProfile200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetProfile200Response(data NullableGetProfile200ResponseData, meta map[string]interface{}) *GetProfile200Response {
	this := GetProfile200Response{}
	this.Data = data
	this.Meta = meta
	return &this
}

// NewGetProfile200ResponseWithDefaults instantiates a new GetProfile200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetProfile200ResponseWithDefaults() *GetProfile200Response {
	this := GetProfile200Response{}
	return &this
}

// GetData returns the Data field value
// If the value is explicit nil, the zero value for GetProfile200ResponseData will be returned
func (o *GetProfile200Response) GetData() GetProfile200ResponseData {
	if o == nil || o.Data.Get() == nil {
		var ret GetProfile200ResponseData
		return ret
	}

	return *o.Data.Get()
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetProfile200Response) GetDataOk() (*GetProfile200ResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data.Get(), o.Data.IsSet()
}

// SetData sets field value
func (o *GetProfile200Response) SetData(v GetProfile200ResponseData) {
	o.Data.Set(&v)
}

// GetMeta returns the Meta field value
func (o *GetProfile200Response) GetMeta() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *GetProfile200Response) GetMetaOk() (map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Meta, true
}

// SetMeta sets field value
func (o *GetProfile200Response) SetMeta(v map[string]interface{}) {
	o.Meta = v
}

func (o GetProfile200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data.Get()
	}
	if true {
		toSerialize["meta"] = o.Meta
	}
	return json.Marshal(toSerialize)
}

type NullableGetProfile200Response struct {
	value *GetProfile200Response
	isSet bool
}

func (v NullableGetProfile200Response) Get() *GetProfile200Response {
	return v.value
}

func (v *NullableGetProfile200Response) Set(val *GetProfile200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetProfile200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetProfile200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetProfile200Response(val *GetProfile200Response) *NullableGetProfile200Response {
	return &NullableGetProfile200Response{value: val, isSet: true}
}

func (v NullableGetProfile200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetProfile200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


