/*
sdk_api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetBoughtItemStocksByWalletAddress200Response struct for GetBoughtItemStocksByWalletAddress200Response
type GetBoughtItemStocksByWalletAddress200Response struct {
	Data GetBoughtItemStocksByWalletAddress200ResponseData `json:"data"`
	Meta map[string]interface{} `json:"meta"`
}

// NewGetBoughtItemStocksByWalletAddress200Response instantiates a new GetBoughtItemStocksByWalletAddress200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetBoughtItemStocksByWalletAddress200Response(data GetBoughtItemStocksByWalletAddress200ResponseData, meta map[string]interface{}) *GetBoughtItemStocksByWalletAddress200Response {
	this := GetBoughtItemStocksByWalletAddress200Response{}
	this.Data = data
	this.Meta = meta
	return &this
}

// NewGetBoughtItemStocksByWalletAddress200ResponseWithDefaults instantiates a new GetBoughtItemStocksByWalletAddress200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetBoughtItemStocksByWalletAddress200ResponseWithDefaults() *GetBoughtItemStocksByWalletAddress200Response {
	this := GetBoughtItemStocksByWalletAddress200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetBoughtItemStocksByWalletAddress200Response) GetData() GetBoughtItemStocksByWalletAddress200ResponseData {
	if o == nil {
		var ret GetBoughtItemStocksByWalletAddress200ResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetBoughtItemStocksByWalletAddress200Response) GetDataOk() (*GetBoughtItemStocksByWalletAddress200ResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetBoughtItemStocksByWalletAddress200Response) SetData(v GetBoughtItemStocksByWalletAddress200ResponseData) {
	o.Data = v
}

// GetMeta returns the Meta field value
func (o *GetBoughtItemStocksByWalletAddress200Response) GetMeta() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *GetBoughtItemStocksByWalletAddress200Response) GetMetaOk() (map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Meta, true
}

// SetMeta sets field value
func (o *GetBoughtItemStocksByWalletAddress200Response) SetMeta(v map[string]interface{}) {
	o.Meta = v
}

func (o GetBoughtItemStocksByWalletAddress200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	if true {
		toSerialize["meta"] = o.Meta
	}
	return json.Marshal(toSerialize)
}

type NullableGetBoughtItemStocksByWalletAddress200Response struct {
	value *GetBoughtItemStocksByWalletAddress200Response
	isSet bool
}

func (v NullableGetBoughtItemStocksByWalletAddress200Response) Get() *GetBoughtItemStocksByWalletAddress200Response {
	return v.value
}

func (v *NullableGetBoughtItemStocksByWalletAddress200Response) Set(val *GetBoughtItemStocksByWalletAddress200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetBoughtItemStocksByWalletAddress200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetBoughtItemStocksByWalletAddress200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetBoughtItemStocksByWalletAddress200Response(val *GetBoughtItemStocksByWalletAddress200Response) *NullableGetBoughtItemStocksByWalletAddress200Response {
	return &NullableGetBoughtItemStocksByWalletAddress200Response{value: val, isSet: true}
}

func (v NullableGetBoughtItemStocksByWalletAddress200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetBoughtItemStocksByWalletAddress200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


