/*
sdk_api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetItemStockPhysicalShippingInfoByItemStockIdRequestData struct for GetItemStockPhysicalShippingInfoByItemStockIdRequestData
type GetItemStockPhysicalShippingInfoByItemStockIdRequestData struct {
	Domain SignatureDomain `json:"domain"`
	PrimaryType string `json:"primaryType"`
	Message GetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage `json:"message"`
	Types map[string]interface{} `json:"types"`
}

// NewGetItemStockPhysicalShippingInfoByItemStockIdRequestData instantiates a new GetItemStockPhysicalShippingInfoByItemStockIdRequestData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetItemStockPhysicalShippingInfoByItemStockIdRequestData(domain SignatureDomain, primaryType string, message GetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage, types map[string]interface{}) *GetItemStockPhysicalShippingInfoByItemStockIdRequestData {
	this := GetItemStockPhysicalShippingInfoByItemStockIdRequestData{}
	this.Domain = domain
	this.PrimaryType = primaryType
	this.Message = message
	this.Types = types
	return &this
}

// NewGetItemStockPhysicalShippingInfoByItemStockIdRequestDataWithDefaults instantiates a new GetItemStockPhysicalShippingInfoByItemStockIdRequestData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetItemStockPhysicalShippingInfoByItemStockIdRequestDataWithDefaults() *GetItemStockPhysicalShippingInfoByItemStockIdRequestData {
	this := GetItemStockPhysicalShippingInfoByItemStockIdRequestData{}
	return &this
}

// GetDomain returns the Domain field value
func (o *GetItemStockPhysicalShippingInfoByItemStockIdRequestData) GetDomain() SignatureDomain {
	if o == nil {
		var ret SignatureDomain
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *GetItemStockPhysicalShippingInfoByItemStockIdRequestData) GetDomainOk() (*SignatureDomain, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *GetItemStockPhysicalShippingInfoByItemStockIdRequestData) SetDomain(v SignatureDomain) {
	o.Domain = v
}

// GetPrimaryType returns the PrimaryType field value
func (o *GetItemStockPhysicalShippingInfoByItemStockIdRequestData) GetPrimaryType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PrimaryType
}

// GetPrimaryTypeOk returns a tuple with the PrimaryType field value
// and a boolean to check if the value has been set.
func (o *GetItemStockPhysicalShippingInfoByItemStockIdRequestData) GetPrimaryTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrimaryType, true
}

// SetPrimaryType sets field value
func (o *GetItemStockPhysicalShippingInfoByItemStockIdRequestData) SetPrimaryType(v string) {
	o.PrimaryType = v
}

// GetMessage returns the Message field value
func (o *GetItemStockPhysicalShippingInfoByItemStockIdRequestData) GetMessage() GetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage {
	if o == nil {
		var ret GetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *GetItemStockPhysicalShippingInfoByItemStockIdRequestData) GetMessageOk() (*GetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *GetItemStockPhysicalShippingInfoByItemStockIdRequestData) SetMessage(v GetItemStockPhysicalShippingInfoByItemStockIdRequestDataMessage) {
	o.Message = v
}

// GetTypes returns the Types field value
func (o *GetItemStockPhysicalShippingInfoByItemStockIdRequestData) GetTypes() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Types
}

// GetTypesOk returns a tuple with the Types field value
// and a boolean to check if the value has been set.
func (o *GetItemStockPhysicalShippingInfoByItemStockIdRequestData) GetTypesOk() (map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Types, true
}

// SetTypes sets field value
func (o *GetItemStockPhysicalShippingInfoByItemStockIdRequestData) SetTypes(v map[string]interface{}) {
	o.Types = v
}

func (o GetItemStockPhysicalShippingInfoByItemStockIdRequestData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["domain"] = o.Domain
	}
	if true {
		toSerialize["primaryType"] = o.PrimaryType
	}
	if true {
		toSerialize["message"] = o.Message
	}
	if true {
		toSerialize["types"] = o.Types
	}
	return json.Marshal(toSerialize)
}

type NullableGetItemStockPhysicalShippingInfoByItemStockIdRequestData struct {
	value *GetItemStockPhysicalShippingInfoByItemStockIdRequestData
	isSet bool
}

func (v NullableGetItemStockPhysicalShippingInfoByItemStockIdRequestData) Get() *GetItemStockPhysicalShippingInfoByItemStockIdRequestData {
	return v.value
}

func (v *NullableGetItemStockPhysicalShippingInfoByItemStockIdRequestData) Set(val *GetItemStockPhysicalShippingInfoByItemStockIdRequestData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetItemStockPhysicalShippingInfoByItemStockIdRequestData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetItemStockPhysicalShippingInfoByItemStockIdRequestData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetItemStockPhysicalShippingInfoByItemStockIdRequestData(val *GetItemStockPhysicalShippingInfoByItemStockIdRequestData) *NullableGetItemStockPhysicalShippingInfoByItemStockIdRequestData {
	return &NullableGetItemStockPhysicalShippingInfoByItemStockIdRequestData{value: val, isSet: true}
}

func (v NullableGetItemStockPhysicalShippingInfoByItemStockIdRequestData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetItemStockPhysicalShippingInfoByItemStockIdRequestData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


