/*
sdk_api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetItemStockPhysicalShippingInfoByItemStockId200Response struct for GetItemStockPhysicalShippingInfoByItemStockId200Response
type GetItemStockPhysicalShippingInfoByItemStockId200Response struct {
	Data ItemStockPhysicalShippingInfo `json:"data"`
	Meta map[string]interface{} `json:"meta"`
}

// NewGetItemStockPhysicalShippingInfoByItemStockId200Response instantiates a new GetItemStockPhysicalShippingInfoByItemStockId200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetItemStockPhysicalShippingInfoByItemStockId200Response(data ItemStockPhysicalShippingInfo, meta map[string]interface{}) *GetItemStockPhysicalShippingInfoByItemStockId200Response {
	this := GetItemStockPhysicalShippingInfoByItemStockId200Response{}
	this.Data = data
	this.Meta = meta
	return &this
}

// NewGetItemStockPhysicalShippingInfoByItemStockId200ResponseWithDefaults instantiates a new GetItemStockPhysicalShippingInfoByItemStockId200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetItemStockPhysicalShippingInfoByItemStockId200ResponseWithDefaults() *GetItemStockPhysicalShippingInfoByItemStockId200Response {
	this := GetItemStockPhysicalShippingInfoByItemStockId200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetItemStockPhysicalShippingInfoByItemStockId200Response) GetData() ItemStockPhysicalShippingInfo {
	if o == nil {
		var ret ItemStockPhysicalShippingInfo
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetItemStockPhysicalShippingInfoByItemStockId200Response) GetDataOk() (*ItemStockPhysicalShippingInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetItemStockPhysicalShippingInfoByItemStockId200Response) SetData(v ItemStockPhysicalShippingInfo) {
	o.Data = v
}

// GetMeta returns the Meta field value
func (o *GetItemStockPhysicalShippingInfoByItemStockId200Response) GetMeta() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *GetItemStockPhysicalShippingInfoByItemStockId200Response) GetMetaOk() (map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Meta, true
}

// SetMeta sets field value
func (o *GetItemStockPhysicalShippingInfoByItemStockId200Response) SetMeta(v map[string]interface{}) {
	o.Meta = v
}

func (o GetItemStockPhysicalShippingInfoByItemStockId200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	if true {
		toSerialize["meta"] = o.Meta
	}
	return json.Marshal(toSerialize)
}

type NullableGetItemStockPhysicalShippingInfoByItemStockId200Response struct {
	value *GetItemStockPhysicalShippingInfoByItemStockId200Response
	isSet bool
}

func (v NullableGetItemStockPhysicalShippingInfoByItemStockId200Response) Get() *GetItemStockPhysicalShippingInfoByItemStockId200Response {
	return v.value
}

func (v *NullableGetItemStockPhysicalShippingInfoByItemStockId200Response) Set(val *GetItemStockPhysicalShippingInfoByItemStockId200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetItemStockPhysicalShippingInfoByItemStockId200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetItemStockPhysicalShippingInfoByItemStockId200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetItemStockPhysicalShippingInfoByItemStockId200Response(val *GetItemStockPhysicalShippingInfoByItemStockId200Response) *NullableGetItemStockPhysicalShippingInfoByItemStockId200Response {
	return &NullableGetItemStockPhysicalShippingInfoByItemStockId200Response{value: val, isSet: true}
}

func (v NullableGetItemStockPhysicalShippingInfoByItemStockId200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetItemStockPhysicalShippingInfoByItemStockId200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


