/*
 * sdk_api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetPaymentIntentByIdResponseBodyDataContractMethodResource struct for GetPaymentIntentByIdResponseBodyDataContractMethodResource
type GetPaymentIntentByIdResponseBodyDataContractMethodResource struct {
	ContractAddress string `json:"contractAddress"`
	NetworkId NetworkId `json:"networkId"`
	ChainType ChainType `json:"chainType"`
	MethodName string `json:"methodName"`
	Abi string `json:"abi"`
	Args []OneOfstringnumberintegerbooleanarrayobject `json:"args"`
}

// NewGetPaymentIntentByIdResponseBodyDataContractMethodResource instantiates a new GetPaymentIntentByIdResponseBodyDataContractMethodResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPaymentIntentByIdResponseBodyDataContractMethodResource(contractAddress string, networkId NetworkId, chainType ChainType, methodName string, abi string, args []OneOfstringnumberintegerbooleanarrayobject) *GetPaymentIntentByIdResponseBodyDataContractMethodResource {
	this := GetPaymentIntentByIdResponseBodyDataContractMethodResource{}
	this.ContractAddress = contractAddress
	this.NetworkId = networkId
	this.ChainType = chainType
	this.MethodName = methodName
	this.Abi = abi
	this.Args = args
	return &this
}

// NewGetPaymentIntentByIdResponseBodyDataContractMethodResourceWithDefaults instantiates a new GetPaymentIntentByIdResponseBodyDataContractMethodResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPaymentIntentByIdResponseBodyDataContractMethodResourceWithDefaults() *GetPaymentIntentByIdResponseBodyDataContractMethodResource {
	this := GetPaymentIntentByIdResponseBodyDataContractMethodResource{}
	return &this
}

// GetContractAddress returns the ContractAddress field value
func (o *GetPaymentIntentByIdResponseBodyDataContractMethodResource) GetContractAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContractAddress
}

// GetContractAddressOk returns a tuple with the ContractAddress field value
// and a boolean to check if the value has been set.
func (o *GetPaymentIntentByIdResponseBodyDataContractMethodResource) GetContractAddressOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ContractAddress, true
}

// SetContractAddress sets field value
func (o *GetPaymentIntentByIdResponseBodyDataContractMethodResource) SetContractAddress(v string) {
	o.ContractAddress = v
}

// GetNetworkId returns the NetworkId field value
func (o *GetPaymentIntentByIdResponseBodyDataContractMethodResource) GetNetworkId() NetworkId {
	if o == nil {
		var ret NetworkId
		return ret
	}

	return o.NetworkId
}

// GetNetworkIdOk returns a tuple with the NetworkId field value
// and a boolean to check if the value has been set.
func (o *GetPaymentIntentByIdResponseBodyDataContractMethodResource) GetNetworkIdOk() (*NetworkId, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.NetworkId, true
}

// SetNetworkId sets field value
func (o *GetPaymentIntentByIdResponseBodyDataContractMethodResource) SetNetworkId(v NetworkId) {
	o.NetworkId = v
}

// GetChainType returns the ChainType field value
func (o *GetPaymentIntentByIdResponseBodyDataContractMethodResource) GetChainType() ChainType {
	if o == nil {
		var ret ChainType
		return ret
	}

	return o.ChainType
}

// GetChainTypeOk returns a tuple with the ChainType field value
// and a boolean to check if the value has been set.
func (o *GetPaymentIntentByIdResponseBodyDataContractMethodResource) GetChainTypeOk() (*ChainType, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ChainType, true
}

// SetChainType sets field value
func (o *GetPaymentIntentByIdResponseBodyDataContractMethodResource) SetChainType(v ChainType) {
	o.ChainType = v
}

// GetMethodName returns the MethodName field value
func (o *GetPaymentIntentByIdResponseBodyDataContractMethodResource) GetMethodName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MethodName
}

// GetMethodNameOk returns a tuple with the MethodName field value
// and a boolean to check if the value has been set.
func (o *GetPaymentIntentByIdResponseBodyDataContractMethodResource) GetMethodNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.MethodName, true
}

// SetMethodName sets field value
func (o *GetPaymentIntentByIdResponseBodyDataContractMethodResource) SetMethodName(v string) {
	o.MethodName = v
}

// GetAbi returns the Abi field value
func (o *GetPaymentIntentByIdResponseBodyDataContractMethodResource) GetAbi() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Abi
}

// GetAbiOk returns a tuple with the Abi field value
// and a boolean to check if the value has been set.
func (o *GetPaymentIntentByIdResponseBodyDataContractMethodResource) GetAbiOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Abi, true
}

// SetAbi sets field value
func (o *GetPaymentIntentByIdResponseBodyDataContractMethodResource) SetAbi(v string) {
	o.Abi = v
}

// GetArgs returns the Args field value
func (o *GetPaymentIntentByIdResponseBodyDataContractMethodResource) GetArgs() []OneOfstringnumberintegerbooleanarrayobject {
	if o == nil {
		var ret []OneOfstringnumberintegerbooleanarrayobject
		return ret
	}

	return o.Args
}

// GetArgsOk returns a tuple with the Args field value
// and a boolean to check if the value has been set.
func (o *GetPaymentIntentByIdResponseBodyDataContractMethodResource) GetArgsOk() (*[]OneOfstringnumberintegerbooleanarrayobject, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Args, true
}

// SetArgs sets field value
func (o *GetPaymentIntentByIdResponseBodyDataContractMethodResource) SetArgs(v []OneOfstringnumberintegerbooleanarrayobject) {
	o.Args = v
}

func (o GetPaymentIntentByIdResponseBodyDataContractMethodResource) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["contractAddress"] = o.ContractAddress
	}
	if true {
		toSerialize["networkId"] = o.NetworkId
	}
	if true {
		toSerialize["chainType"] = o.ChainType
	}
	if true {
		toSerialize["methodName"] = o.MethodName
	}
	if true {
		toSerialize["abi"] = o.Abi
	}
	if true {
		toSerialize["args"] = o.Args
	}
	return json.Marshal(toSerialize)
}

type NullableGetPaymentIntentByIdResponseBodyDataContractMethodResource struct {
	value *GetPaymentIntentByIdResponseBodyDataContractMethodResource
	isSet bool
}

func (v NullableGetPaymentIntentByIdResponseBodyDataContractMethodResource) Get() *GetPaymentIntentByIdResponseBodyDataContractMethodResource {
	return v.value
}

func (v *NullableGetPaymentIntentByIdResponseBodyDataContractMethodResource) Set(val *GetPaymentIntentByIdResponseBodyDataContractMethodResource) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPaymentIntentByIdResponseBodyDataContractMethodResource) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPaymentIntentByIdResponseBodyDataContractMethodResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPaymentIntentByIdResponseBodyDataContractMethodResource(val *GetPaymentIntentByIdResponseBodyDataContractMethodResource) *NullableGetPaymentIntentByIdResponseBodyDataContractMethodResource {
	return &NullableGetPaymentIntentByIdResponseBodyDataContractMethodResource{value: val, isSet: true}
}

func (v NullableGetPaymentIntentByIdResponseBodyDataContractMethodResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPaymentIntentByIdResponseBodyDataContractMethodResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


