/*
sdk_api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreateOrUpdateItemStockPhysicalShippingInfoRequest struct for CreateOrUpdateItemStockPhysicalShippingInfoRequest
type CreateOrUpdateItemStockPhysicalShippingInfoRequest struct {
	Data CreateOrUpdateItemStockPhysicalShippingInfoRequestData `json:"data"`
	Signature string `json:"signature"`
}

// NewCreateOrUpdateItemStockPhysicalShippingInfoRequest instantiates a new CreateOrUpdateItemStockPhysicalShippingInfoRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrUpdateItemStockPhysicalShippingInfoRequest(data CreateOrUpdateItemStockPhysicalShippingInfoRequestData, signature string) *CreateOrUpdateItemStockPhysicalShippingInfoRequest {
	this := CreateOrUpdateItemStockPhysicalShippingInfoRequest{}
	this.Data = data
	this.Signature = signature
	return &this
}

// NewCreateOrUpdateItemStockPhysicalShippingInfoRequestWithDefaults instantiates a new CreateOrUpdateItemStockPhysicalShippingInfoRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrUpdateItemStockPhysicalShippingInfoRequestWithDefaults() *CreateOrUpdateItemStockPhysicalShippingInfoRequest {
	this := CreateOrUpdateItemStockPhysicalShippingInfoRequest{}
	return &this
}

// GetData returns the Data field value
func (o *CreateOrUpdateItemStockPhysicalShippingInfoRequest) GetData() CreateOrUpdateItemStockPhysicalShippingInfoRequestData {
	if o == nil {
		var ret CreateOrUpdateItemStockPhysicalShippingInfoRequestData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateOrUpdateItemStockPhysicalShippingInfoRequest) GetDataOk() (*CreateOrUpdateItemStockPhysicalShippingInfoRequestData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreateOrUpdateItemStockPhysicalShippingInfoRequest) SetData(v CreateOrUpdateItemStockPhysicalShippingInfoRequestData) {
	o.Data = v
}

// GetSignature returns the Signature field value
func (o *CreateOrUpdateItemStockPhysicalShippingInfoRequest) GetSignature() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value
// and a boolean to check if the value has been set.
func (o *CreateOrUpdateItemStockPhysicalShippingInfoRequest) GetSignatureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Signature, true
}

// SetSignature sets field value
func (o *CreateOrUpdateItemStockPhysicalShippingInfoRequest) SetSignature(v string) {
	o.Signature = v
}

func (o CreateOrUpdateItemStockPhysicalShippingInfoRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	if true {
		toSerialize["signature"] = o.Signature
	}
	return json.Marshal(toSerialize)
}

type NullableCreateOrUpdateItemStockPhysicalShippingInfoRequest struct {
	value *CreateOrUpdateItemStockPhysicalShippingInfoRequest
	isSet bool
}

func (v NullableCreateOrUpdateItemStockPhysicalShippingInfoRequest) Get() *CreateOrUpdateItemStockPhysicalShippingInfoRequest {
	return v.value
}

func (v *NullableCreateOrUpdateItemStockPhysicalShippingInfoRequest) Set(val *CreateOrUpdateItemStockPhysicalShippingInfoRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrUpdateItemStockPhysicalShippingInfoRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrUpdateItemStockPhysicalShippingInfoRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrUpdateItemStockPhysicalShippingInfoRequest(val *CreateOrUpdateItemStockPhysicalShippingInfoRequest) *NullableCreateOrUpdateItemStockPhysicalShippingInfoRequest {
	return &NullableCreateOrUpdateItemStockPhysicalShippingInfoRequest{value: val, isSet: true}
}

func (v NullableCreateOrUpdateItemStockPhysicalShippingInfoRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrUpdateItemStockPhysicalShippingInfoRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


