/*
 * sdk_api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InlineObject3 struct for InlineObject3
type InlineObject3 struct {
	// Item id that will be purchased
	ItemId string `json:"itemId"`
	// Buyer wallet address
	ToAddress string `json:"toAddress"`
	UserResidence UserResidence `json:"userResidence"`
}

// NewInlineObject3 instantiates a new InlineObject3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject3(itemId string, toAddress string, userResidence UserResidence) *InlineObject3 {
	this := InlineObject3{}
	this.ItemId = itemId
	this.ToAddress = toAddress
	this.UserResidence = userResidence
	return &this
}

// NewInlineObject3WithDefaults instantiates a new InlineObject3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject3WithDefaults() *InlineObject3 {
	this := InlineObject3{}
	return &this
}

// GetItemId returns the ItemId field value
func (o *InlineObject3) GetItemId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ItemId
}

// GetItemIdOk returns a tuple with the ItemId field value
// and a boolean to check if the value has been set.
func (o *InlineObject3) GetItemIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ItemId, true
}

// SetItemId sets field value
func (o *InlineObject3) SetItemId(v string) {
	o.ItemId = v
}

// GetToAddress returns the ToAddress field value
func (o *InlineObject3) GetToAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ToAddress
}

// GetToAddressOk returns a tuple with the ToAddress field value
// and a boolean to check if the value has been set.
func (o *InlineObject3) GetToAddressOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ToAddress, true
}

// SetToAddress sets field value
func (o *InlineObject3) SetToAddress(v string) {
	o.ToAddress = v
}

// GetUserResidence returns the UserResidence field value
func (o *InlineObject3) GetUserResidence() UserResidence {
	if o == nil {
		var ret UserResidence
		return ret
	}

	return o.UserResidence
}

// GetUserResidenceOk returns a tuple with the UserResidence field value
// and a boolean to check if the value has been set.
func (o *InlineObject3) GetUserResidenceOk() (*UserResidence, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.UserResidence, true
}

// SetUserResidence sets field value
func (o *InlineObject3) SetUserResidence(v UserResidence) {
	o.UserResidence = v
}

func (o InlineObject3) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["itemId"] = o.ItemId
	}
	if true {
		toSerialize["toAddress"] = o.ToAddress
	}
	if true {
		toSerialize["userResidence"] = o.UserResidence
	}
	return json.Marshal(toSerialize)
}

type NullableInlineObject3 struct {
	value *InlineObject3
	isSet bool
}

func (v NullableInlineObject3) Get() *InlineObject3 {
	return v.value
}

func (v *NullableInlineObject3) Set(val *InlineObject3) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject3) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject3(val *InlineObject3) *NullableInlineObject3 {
	return &NullableInlineObject3{value: val, isSet: true}
}

func (v NullableInlineObject3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


