/*
sdk_api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetPaymentIntentById200Response struct for GetPaymentIntentById200Response
type GetPaymentIntentById200Response struct {
	Data GetPaymentIntentByIdResponseBodyData `json:"data"`
	Meta map[string]interface{} `json:"meta"`
}

// NewGetPaymentIntentById200Response instantiates a new GetPaymentIntentById200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPaymentIntentById200Response(data GetPaymentIntentByIdResponseBodyData, meta map[string]interface{}) *GetPaymentIntentById200Response {
	this := GetPaymentIntentById200Response{}
	this.Data = data
	this.Meta = meta
	return &this
}

// NewGetPaymentIntentById200ResponseWithDefaults instantiates a new GetPaymentIntentById200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPaymentIntentById200ResponseWithDefaults() *GetPaymentIntentById200Response {
	this := GetPaymentIntentById200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetPaymentIntentById200Response) GetData() GetPaymentIntentByIdResponseBodyData {
	if o == nil {
		var ret GetPaymentIntentByIdResponseBodyData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetPaymentIntentById200Response) GetDataOk() (*GetPaymentIntentByIdResponseBodyData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetPaymentIntentById200Response) SetData(v GetPaymentIntentByIdResponseBodyData) {
	o.Data = v
}

// GetMeta returns the Meta field value
func (o *GetPaymentIntentById200Response) GetMeta() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *GetPaymentIntentById200Response) GetMetaOk() (map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Meta, true
}

// SetMeta sets field value
func (o *GetPaymentIntentById200Response) SetMeta(v map[string]interface{}) {
	o.Meta = v
}

func (o GetPaymentIntentById200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	if true {
		toSerialize["meta"] = o.Meta
	}
	return json.Marshal(toSerialize)
}

type NullableGetPaymentIntentById200Response struct {
	value *GetPaymentIntentById200Response
	isSet bool
}

func (v NullableGetPaymentIntentById200Response) Get() *GetPaymentIntentById200Response {
	return v.value
}

func (v *NullableGetPaymentIntentById200Response) Set(val *GetPaymentIntentById200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPaymentIntentById200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPaymentIntentById200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPaymentIntentById200Response(val *GetPaymentIntentById200Response) *NullableGetPaymentIntentById200Response {
	return &NullableGetPaymentIntentById200Response{value: val, isSet: true}
}

func (v NullableGetPaymentIntentById200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPaymentIntentById200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


